// Transcribed from docs/*.md hotel research — see those files for source. Do not invent missing data; null means unverified.

export interface HotelSupplierSeedRow {
  hotelName: string;
  destination:
    | "Srinagar"
    | "Pahalgam"
    | "Gulmarg / Tangmarg"
    | "Sonamarg"
    | "Gurez"
    | "Leh / Ladakh"
    | "Kargil"
    | "Katra / Vaishno Devi"
    | "Uri / Kaman Setu";
  category: "BUDGET" | "DELUXE" | "PREMIUM";
  property: {
    location: string | null;
    contactPerson: string | null;
    phone: string | null;
    email: string | null;
    mapUrl: string | null;
  };
  notes: string | null;
}

export const HOTEL_SUPPLIERS_SEED: HotelSupplierSeedRow[] = [
  // ===== Srinagar (docs/srinagar-hotels.md) =====
  // Budget
  { hotelName: "Hotel Downtown", destination: "Srinagar", category: "BUDGET", property: { location: "Munawara Abad, near Dal Lake", contactPerson: null, phone: "+91 99066 97520", email: "sales@hoteldowntown.us", mapUrl: "https://www.google.com/maps/search/?api=1&query=Hotel+Downtown+Srinagar" }, notes: "4.7★ / 2,698 reviews" },
  { hotelName: "Hotel Star of Kashmir", destination: "Srinagar", category: "BUDGET", property: { location: "Airport Road, Hyderpora", contactPerson: null, phone: "+91 94190 79409", email: null, mapUrl: "https://www.google.com/maps/search/?api=1&query=Hotel+Star+of+Kashmir+Srinagar" }, notes: "4.5★ / 2,996 reviews" },
  { hotelName: "Hotel Palm Spring", destination: "Srinagar", category: "BUDGET", property: { location: "Wazir Bagh", contactPerson: null, phone: "+91 95415 44609", email: null, mapUrl: "https://www.google.com/maps/search/?api=1&query=Hotel+Palm+Spring+Srinagar" }, notes: "4.6★ / 1,548 reviews" },
  { hotelName: "Elaf Residency", destination: "Srinagar", category: "BUDGET", property: { location: "Gogji Bagh / Jawahar Nagar", contactPerson: null, phone: "+91 95412 31601", email: null, mapUrl: "https://www.google.com/maps/search/?api=1&query=Elaf+Residency+Srinagar" }, notes: "4.9★ / 630 reviews" },
  { hotelName: "Villa 67 Srinagar", destination: "Srinagar", category: "BUDGET", property: { location: "Buchwara, Durgjan", contactPerson: null, phone: null, email: null, mapUrl: "https://www.google.com/maps/search/?api=1&query=Villa+67+Srinagar" }, notes: "4.9★ / 213 reviews" },
  { hotelName: "Kareem Residency", destination: "Srinagar", category: "BUDGET", property: { location: "Bishember Nagar / Chinar Bagh", contactPerson: null, phone: "+91 70068 84661", email: null, mapUrl: "https://www.google.com/maps/search/?api=1&query=Kareem+Residency+Srinagar" }, notes: "4.7★ / 1,792 reviews" },
  // Deluxe
  { hotelName: "Hotel Meerz", destination: "Srinagar", category: "DELUXE", property: { location: "Khayam Chowk / Dalgate", contactPerson: null, phone: "+91 88990 04681 / 0194 2477104", email: "info@hotelmeerz.com", mapUrl: "https://www.google.com/maps/search/?api=1&query=Hotel+Meerz+Srinagar" }, notes: "4.5★ / 1,194 reviews" },
  { hotelName: "The Kabo", destination: "Srinagar", category: "DELUXE", property: { location: "Wazir Bagh", contactPerson: null, phone: "+91 194 2313401", email: null, mapUrl: "https://www.google.com/maps/search/?api=1&query=The+Kabo+Srinagar" }, notes: "4.6★ / 671 reviews" },
  { hotelName: "Hotel Royal Heritage", destination: "Srinagar", category: "DELUXE", property: { location: "M.A. Link Road / Munawara Abad", contactPerson: null, phone: "+91 194 2486277", email: null, mapUrl: "https://www.google.com/maps/search/?api=1&query=Hotel+Royal+Heritage+Srinagar" }, notes: "4.2★ / 1,061 reviews" },
  { hotelName: "Grand Mir International", destination: "Srinagar", category: "DELUXE", property: { location: "Wazir Bagh", contactPerson: null, phone: null, email: null, mapUrl: "https://www.google.com/maps/search/?api=1&query=Grand+Mir+International+Srinagar" }, notes: "4.5★ / 615 reviews" },
  { hotelName: "Hotel Meridien", destination: "Srinagar", category: "DELUXE", property: { location: "Convent Road, Rajbagh", contactPerson: null, phone: "+91 97966 31117", email: null, mapUrl: "https://www.google.com/maps/search/?api=1&query=Hotel+Meridien+Srinagar" }, notes: "4.1★ / 407 reviews" },
  { hotelName: "The Grand Mamta", destination: "Srinagar", category: "DELUXE", property: { location: "Dalgate / near Dal Lake", contactPerson: null, phone: "+91 97969 99321 / +91 97969 99306", email: "reservation@thegrandmamta.co.in", mapUrl: "https://www.google.com/maps/search/?api=1&query=The+Grand+Mamta+Srinagar" }, notes: "4.1★ / 2,803 reviews" },
  // Premium
  { hotelName: "Radisson Collection Hotel & Spa, Riverfront Srinagar", destination: "Srinagar", category: "PREMIUM", property: { location: "Rajbagh / Jehlum Bund", contactPerson: null, phone: "+91 194 2310111", email: null, mapUrl: "https://www.google.com/maps/search/?api=1&query=Radisson+Collection+Hotel+%26+Spa+Riverfront+Srinagar" }, notes: "4.8★ / 1,245 reviews" },
  { hotelName: "Radisson Hotel Srinagar", destination: "Srinagar", category: "PREMIUM", property: { location: "M.A. Road / Kashmir Golf Course", contactPerson: null, phone: "+91 194 2484000", email: null, mapUrl: "https://www.google.com/maps/search/?api=1&query=Radisson+Hotel+Srinagar" }, notes: "4.1★ / 2,007 reviews" },
  { hotelName: "Taj Dal View, Srinagar", destination: "Srinagar", category: "PREMIUM", property: { location: "Kralsangri, Brein", contactPerson: null, phone: "+91 194 2461111 / +91 97969 99933", email: "tajdalview.srinagar@tajhotels.com", mapUrl: "https://www.google.com/maps/search/?api=1&query=Taj+Dal+View+Srinagar" }, notes: "4.5★ / ~4,940 reviews" },
  { hotelName: "The LaLiT Grand Palace Srinagar", destination: "Srinagar", category: "PREMIUM", property: { location: "Gupkar Road", contactPerson: null, phone: "+91 194 2501001", email: "srinagar@thelalit.com", mapUrl: "https://www.google.com/maps/search/?api=1&query=The+LaLiT+Grand+Palace+Srinagar" }, notes: "4.3★ / ~3,378 reviews" },
  { hotelName: "The Other House", destination: "Srinagar", category: "PREMIUM", property: { location: "Khimber / Gassu", contactPerson: null, phone: "+91 98116 011346", email: null, mapUrl: "https://www.google.com/maps/search/?api=1&query=The+Other+House+Srinagar" }, notes: "5.0★ / 58 reviews" },
  { hotelName: "Heritage Bungalow", destination: "Srinagar", category: "PREMIUM", property: { location: "Rajbagh", contactPerson: null, phone: "+91 190 3407514", email: null, mapUrl: "https://www.google.com/maps/search/?api=1&query=Heritage+Bungalow+Srinagar" }, notes: "4.3★ / 278 reviews" },

  // ===== Pahalgam (docs/pahalgam-hotels.md) =====
  // Budget
  { hotelName: "New Relax Inn Pahalgam", destination: "Pahalgam", category: "BUDGET", property: { location: "Pahalgam", contactPerson: null, phone: "+91 91035 50919 / +91 99066 19223 / 01936 295293", email: "reservations.newrelaxinn@gmail.com", mapUrl: "https://www.google.com/maps/search/?api=1&query=New+Relax+Inn+Pahalgam" }, notes: "4.7★*" },
  { hotelName: "Bentes Lodge", destination: "Pahalgam", category: "BUDGET", property: { location: "Pahalgam", contactPerson: null, phone: null, email: null, mapUrl: "https://www.google.com/maps/search/?api=1&query=Bentes+Lodge+Pahalgam" }, notes: "4.8★" },
  { hotelName: "Snow Peak Guest House Pahalgam", destination: "Pahalgam", category: "BUDGET", property: { location: "Pahalgam", contactPerson: null, phone: null, email: null, mapUrl: "https://www.google.com/maps/search/?api=1&query=Snow+Peak+Guest+House+Pahalgam" }, notes: "4.6★" },
  { hotelName: "Hotel Baisaran Pahalgam", destination: "Pahalgam", category: "BUDGET", property: { location: "Chandanwari Road, Opp. Poshwan Park", contactPerson: null, phone: "+91 96226 67175", email: "info@hotelbaisaranpahalgam.com", mapUrl: "https://www.google.com/maps/search/?api=1&query=Hotel+Baisaran+Pahalgam" }, notes: null },
  { hotelName: "Hotel Outlook Pahalgam", destination: "Pahalgam", category: "BUDGET", property: { location: "Pahalgam", contactPerson: null, phone: null, email: null, mapUrl: "https://www.google.com/maps/search/?api=1&query=Hotel+Outlook+Pahalgam" }, notes: "4.3★" },
  { hotelName: "Hotel Pahalgam Star", destination: "Pahalgam", category: "BUDGET", property: { location: "Lidroo, Pahalgam", contactPerson: null, phone: "+91 99068 04260", email: null, mapUrl: "https://www.google.com/maps/search/?api=1&query=Hotel+Pahalgam+Star" }, notes: "4.7★" },
  // Deluxe
  { hotelName: "Hotel Woodstock Pahalgam", destination: "Pahalgam", category: "DELUXE", property: { location: "Pahalgam Bazaar", contactPerson: null, phone: "+91 94195 94171 / +91 70065 56603 / 01936 243259", email: "hotelwoodstockpahalgam@gmail.com", mapUrl: "https://www.google.com/maps/search/?api=1&query=Hotel+Woodstock+Pahalgam" }, notes: null },
  { hotelName: "Pahalgam Hotel", destination: "Pahalgam", category: "DELUXE", property: { location: "Main Market, Chandanwari, Pahalgam", contactPerson: null, phone: "+91 94190 49555", email: null, mapUrl: "https://www.google.com/maps/search/?api=1&query=Pahalgam+Hotel" }, notes: "4.3★" },
  { hotelName: "The Villagio", destination: "Pahalgam", category: "DELUXE", property: { location: "Amarnath Yatra Camp Site, Pahalgam", contactPerson: null, phone: "+91 95968 87571", email: null, mapUrl: "https://www.google.com/maps/search/?api=1&query=The+Villagio+Pahalgam" }, notes: "4.3★" },
  { hotelName: "Hotel Heevan Pahalgam", destination: "Pahalgam", category: "DELUXE", property: { location: "Opposite Amusement Park, Pahalgam", contactPerson: null, phone: "+91 194 250 1395", email: null, mapUrl: "https://www.google.com/maps/search/?api=1&query=Hotel+Heevan+Pahalgam" }, notes: "4.2★" },
  { hotelName: "Royal Grandiose Pahalgam", destination: "Pahalgam", category: "DELUXE", property: { location: "Circuit Road, Pahalgam", contactPerson: null, phone: "+91 1936 243 555", email: null, mapUrl: "https://www.google.com/maps/search/?api=1&query=Royal+Grandiose+Pahalgam" }, notes: "4.3★" },
  { hotelName: "The Chinar Resort & Spa", destination: "Pahalgam", category: "DELUXE", property: { location: "Pahalgam", contactPerson: null, phone: null, email: null, mapUrl: "https://www.google.com/maps/search/?api=1&query=The+Chinar+Resort+%26+Spa+Pahalgam" }, notes: null },
  { hotelName: "The Walnut Creek Pahalgam", destination: "Pahalgam", category: "DELUXE", property: { location: "Pahalgam", contactPerson: null, phone: null, email: null, mapUrl: "https://www.google.com/maps/search/?api=1&query=The+Walnut+Creek+Pahalgam" }, notes: "4.5★*" },
  // Premium
  { hotelName: "Welcomhotel by ITC Hotels, Pine N Peak Pahalgam", destination: "Pahalgam", category: "PREMIUM", property: { location: "Aru Road, near Amusement Park", contactPerson: null, phone: "+91 1936 243210 / +91 1936 243211 / +91 99066 25611 / +91 94190 45325", email: "reservations@itchotels.com / sales@ahadhotelsandresorts.com", mapUrl: "https://www.google.com/maps/search/?api=1&query=Welcomhotel+Pine+N+Peak+Pahalgam" }, notes: "4.8★" },
  { hotelName: "Radisson Golf Resort Pahalgam", destination: "Pahalgam", category: "PREMIUM", property: { location: "Adjacent to Pahalgam Golf Course", contactPerson: null, phone: "+91 77808 68862", email: "reservations.pahalgam@radisson.com", mapUrl: "https://www.google.com/maps/search/?api=1&query=Radisson+Golf+Resort+Pahalgam" }, notes: "4.4★" },
  { hotelName: "Fortune Pahalgam", destination: "Pahalgam", category: "PREMIUM", property: { location: "Circuit Road, Ganishbal", contactPerson: null, phone: "+91 1936 351010 / +91 1936 351020", email: "pahalgam@fortunehotels.in", mapUrl: "https://www.google.com/maps/search/?api=1&query=Fortune+Pahalgam" }, notes: null },
  { hotelName: "Royal Hillton Pahalgam", destination: "Pahalgam", category: "PREMIUM", property: { location: "Circuit Road, Pahalgam", contactPerson: null, phone: "+91 70512 78606", email: "reservations@royalhillton.com", mapUrl: "https://www.google.com/maps/search/?api=1&query=Royal+Hillton+Pahalgam" }, notes: null },
  { hotelName: "Mountnoor Sarovar Premiere Pahalgam", destination: "Pahalgam", category: "PREMIUM", property: { location: "Pahalgam", contactPerson: null, phone: null, email: null, mapUrl: "https://www.google.com/maps/search/?api=1&query=Mountnoor+Sarovar+Premiere+Pahalgam" }, notes: "5.0★*" },
  { hotelName: "Hotel Heevan Pahalgam River Front Luxury", destination: "Pahalgam", category: "PREMIUM", property: { location: "Pahalgam / Lidder River", contactPerson: null, phone: "+91 194 250 1395", email: null, mapUrl: "https://www.google.com/maps/search/?api=1&query=Hotel+Heevan+Pahalgam" }, notes: "4.2★" },

  // ===== Gulmarg / Tangmarg (docs/tangmarg-gulmarg.md) =====
  // Budget
  { hotelName: "The Gulmarg Palace", destination: "Gulmarg / Tangmarg", category: "BUDGET", property: { location: "Tangmarg, Gulmarg", contactPerson: null, phone: "+91 70065 15787", email: null, mapUrl: "https://www.google.com/maps/search/?api=1&query=The+Gulmarg+Palace+Tangmarg" }, notes: "4.7★ / 486 reviews" },
  { hotelName: "Hotel JB Palace Tangmarg", destination: "Gulmarg / Tangmarg", category: "BUDGET", property: { location: "Gateway of Gulmarg, Tangmarg", contactPerson: null, phone: "+91 91034 43377", email: null, mapUrl: "https://www.google.com/maps/search/?api=1&query=Hotel+JB+Palace+Tangmarg" }, notes: "4.4★ / 188 reviews" },
  { hotelName: "GULMARG GS Residency Hotel & Restaurant", destination: "Gulmarg / Tangmarg", category: "BUDGET", property: { location: "Kunzer / Srinagar-Gulmarg Road", contactPerson: null, phone: "+91 95412 17704", email: null, mapUrl: "https://www.google.com/maps/search/?api=1&query=Gulmarg+GS+Residency+Hotel+and+Restaurant" }, notes: "4.7★ / 829 reviews" },
  { hotelName: "Hotel Gulmarg House", destination: "Gulmarg / Tangmarg", category: "BUDGET", property: { location: "Qazipora, Tangmarg", contactPerson: null, phone: "+91 88990 04526 / +91 88990 04527", email: "hotelgulmarghouse@gmail.com", mapUrl: "https://www.google.com/maps/search/?api=1&query=Hotel+Gulmarg+House+Tangmarg" }, notes: null },
  { hotelName: "Habib Guest House", destination: "Gulmarg / Tangmarg", category: "BUDGET", property: { location: "Qazipora, Tangmarg", contactPerson: null, phone: "+91 78895 30074", email: null, mapUrl: "https://www.google.com/maps/search/?api=1&query=Habib+Guest+House+Tangmarg" }, notes: "4.6★ / 133 reviews" },
  { hotelName: "Dewan Guest House", destination: "Gulmarg / Tangmarg", category: "BUDGET", property: { location: "Iqbal Colony, Tangmarg", contactPerson: null, phone: "+91 70063 58651", email: null, mapUrl: "https://www.google.com/maps/search/?api=1&query=Dewan+Guest+House+Tangmarg" }, notes: "4.9★ / 252 reviews" },
  // Deluxe
  { hotelName: "Hotel Gulmarg Countryside", destination: "Gulmarg / Tangmarg", category: "DELUXE", property: { location: "Qazipora, Tangmarg", contactPerson: null, phone: "+91 97977 72773", email: null, mapUrl: "https://www.google.com/maps/search/?api=1&query=Hotel+Gulmarg+Countryside" }, notes: "4.8★ / 527 reviews" },
  { hotelName: "Pine View Hotel", destination: "Gulmarg / Tangmarg", category: "DELUXE", property: { location: "Tangmarg-Gulmarg Road", contactPerson: null, phone: "+91 99066 89312", email: "reservation@pineviewhotels.com", mapUrl: "https://www.google.com/maps/search/?api=1&query=Pine+View+Hotel+Tangmarg" }, notes: null },
  { hotelName: "Royal Park Hotel", destination: "Gulmarg / Tangmarg", category: "DELUXE", property: { location: "Gulmarg Road, Nagbal", contactPerson: null, phone: "+91 94190 00104 / +91 98987 62174", email: "reservation@hotelroyalpark.net", mapUrl: "https://www.google.com/maps/search/?api=1&query=Royal+Park+Hotel+Gulmarg" }, notes: null },
  { hotelName: "Hotel Nedou's", destination: "Gulmarg / Tangmarg", category: "DELUXE", property: { location: "Ski Institute Road, Gulmarg", contactPerson: null, phone: "+91 70068 18341", email: null, mapUrl: "https://www.google.com/maps/search/?api=1&query=Hotel+Nedous+Gulmarg" }, notes: "4.7★ / 708 reviews" },
  { hotelName: "Shaw Resort 11", destination: "Gulmarg / Tangmarg", category: "DELUXE", property: { location: "Site 1, Gulmarg, Nagbal", contactPerson: null, phone: "+91 99064 89289", email: null, mapUrl: "https://www.google.com/maps/search/?api=1&query=Shaw+Resort+11+Gulmarg" }, notes: "4.7★ / 657 reviews" },
  { hotelName: "The Royal Terrain", destination: "Gulmarg / Tangmarg", category: "DELUXE", property: { location: "Qazipora, Gulmarg", contactPerson: null, phone: "+91 94190 06321", email: null, mapUrl: "https://www.google.com/maps/search/?api=1&query=The+Royal+Terrain+Gulmarg" }, notes: "4.7★ / 205 reviews" },
  { hotelName: "Hotel Hilltop", destination: "Gulmarg / Tangmarg", category: "DELUXE", property: { location: "Opp. Ice Skating Rink, Gulmarg", contactPerson: null, phone: "+91 95425 4477 / +91 95425 4445 / +91 95425 4559", email: "reservations@hilltophotelgulmarg.com", mapUrl: "https://www.google.com/maps/search/?api=1&query=Hotel+Hilltop+Gulmarg" }, notes: "4.1★ / 1,733 reviews" },
  // Premium
  { hotelName: "The Khyber Himalayan Resort & Spa", destination: "Gulmarg / Tangmarg", category: "PREMIUM", property: { location: "Hotel Khyber Road, near Gulmarg Gondola", contactPerson: null, phone: "+91 1954 350666 / +91 194 3503222", email: "info.gulmarg@khyberhotels.com / reservations@khyberhotels.com", mapUrl: "https://www.google.com/maps/search/?api=1&query=The+Khyber+Himalayan+Resort+%26+Spa+Gulmarg" }, notes: null },
  { hotelName: "The Pine Palace Resort", destination: "Gulmarg / Tangmarg", category: "PREMIUM", property: { location: "Gulmarg", contactPerson: null, phone: "+91 1954 254466 / +91 99064 44898", email: "info@pinepalaceresort.com", mapUrl: "https://www.google.com/maps/search/?api=1&query=The+Pine+Palace+Resort+Gulmarg" }, notes: null },
  { hotelName: "Highlands Park", destination: "Gulmarg / Tangmarg", category: "PREMIUM", property: { location: "Church Road, Gulmarg", contactPerson: null, phone: "+91 1954 254491", email: "highlandspark@gmail.com", mapUrl: "https://www.google.com/maps/search/?api=1&query=Hotel+Highlands+Park+Gulmarg" }, notes: null },
  { hotelName: "Kolahoi Green Heights", destination: "Gulmarg / Tangmarg", category: "PREMIUM", property: { location: "Gulmarg", contactPerson: null, phone: null, email: null, mapUrl: "https://www.google.com/maps/search/?api=1&query=Kolahoi+Green+Heights+Gulmarg" }, notes: "4.3★ / 1,082 reviews" },
  { hotelName: "Welcome Hotel Gulmarg", destination: "Gulmarg / Tangmarg", category: "PREMIUM", property: { location: "Gulmarg", contactPerson: null, phone: null, email: null, mapUrl: "https://www.google.com/maps/search/?api=1&query=Welcome+Hotel+Gulmarg" }, notes: "4.0★ / 1,411 reviews" },
  { hotelName: "Hotel Alpine Ridge", destination: "Gulmarg / Tangmarg", category: "PREMIUM", property: { location: "Gulmarg", contactPerson: null, phone: null, email: null, mapUrl: "https://www.google.com/maps/search/?api=1&query=Hotel+Alpine+Ridge+Gulmarg" }, notes: null },

  // ===== Sonamarg (docs/sonamarg-hotels.md) =====
  // Budget
  { hotelName: "Hotel Mughal India, Sonmarg", destination: "Sonamarg", category: "BUDGET", property: { location: "Sonamarg", contactPerson: null, phone: "+91 88999 74333", email: null, mapUrl: "https://www.google.com/maps/search/?api=1&query=Hotel+Mughal+India+Sonamarg" }, notes: "4.8★" },
  { hotelName: "Hotel Thajwass Glacier", destination: "Sonamarg", category: "BUDGET", property: { location: "Sonamarg", contactPerson: null, phone: null, email: null, mapUrl: "https://www.google.com/maps/search/?api=1&query=Hotel+Thajwass+Glacier+Sonamarg" }, notes: null },
  { hotelName: "Hotel Sonamarg Palace", destination: "Sonamarg", category: "BUDGET", property: { location: "Sonamarg", contactPerson: null, phone: null, email: null, mapUrl: "https://www.google.com/maps/search/?api=1&query=Hotel+Sonamarg+Palace" }, notes: null },
  { hotelName: "Hotel Sonamarg Glacier", destination: "Sonamarg", category: "BUDGET", property: { location: "Sonamarg", contactPerson: null, phone: null, email: null, mapUrl: "https://www.google.com/maps/search/?api=1&query=Hotel+Sonamarg+Glacier" }, notes: null },
  { hotelName: "Hotel Sonamarg Inn", destination: "Sonamarg", category: "BUDGET", property: { location: "Sonamarg", contactPerson: null, phone: null, email: null, mapUrl: "https://www.google.com/maps/search/?api=1&query=Hotel+Sonamarg+Inn" }, notes: null },
  { hotelName: "Sonamarg Snow View", destination: "Sonamarg", category: "BUDGET", property: { location: "Sonamarg / near main market", contactPerson: null, phone: "+91 88999 40290", email: null, mapUrl: "https://www.google.com/maps/search/?api=1&query=Sonamarg+Snow+View" }, notes: "4.7★" },
  // Deluxe
  { hotelName: "Hotel Village Walk", destination: "Sonamarg", category: "DELUXE", property: { location: "Sonamarg", contactPerson: null, phone: null, email: null, mapUrl: "https://www.google.com/maps/search/?api=1&query=Hotel+Village+Walk+Sonamarg" }, notes: null },
  { hotelName: "Arco Hotels & Resorts", destination: "Sonamarg", category: "DELUXE", property: { location: "Gaad-Koul, Sonamarg", contactPerson: null, phone: "+91 95967 55476 / +91 95967 55461", email: "sonamarg@arcohotels.in / reservation@arcohotels.in", mapUrl: "https://www.google.com/maps/search/?api=1&query=Arco+Hotels+%26+Resorts+Sonamarg" }, notes: "4.8★" },
  { hotelName: "Hotel Akbar Sonamarg", destination: "Sonamarg", category: "DELUXE", property: { location: "Sonamarg", contactPerson: null, phone: null, email: null, mapUrl: "https://www.google.com/maps/search/?api=1&query=Hotel+Akbar+Sonamarg" }, notes: null },
  { hotelName: "Imperial Resorts", destination: "Sonamarg", category: "DELUXE", property: { location: "Sonamarg", contactPerson: null, phone: null, email: null, mapUrl: "https://www.google.com/maps/search/?api=1&query=Imperial+Resorts+Sonamarg" }, notes: null },
  { hotelName: "The Vista Hotel Sonamarg", destination: "Sonamarg", category: "DELUXE", property: { location: "Sonamarg", contactPerson: null, phone: null, email: null, mapUrl: "https://www.google.com/maps/search/?api=1&query=The+Vista+Hotel+Sonamarg" }, notes: null },
  { hotelName: "Hotel Tranquil Retreat", destination: "Sonamarg", category: "DELUXE", property: { location: "Sonamarg", contactPerson: null, phone: null, email: null, mapUrl: "https://www.google.com/maps/search/?api=1&query=Hotel+Tranquil+Retreat+Sonamarg" }, notes: null },
  { hotelName: "Grand Hayat Sonamarg", destination: "Sonamarg", category: "DELUXE", property: { location: "Sonamarg", contactPerson: null, phone: null, email: null, mapUrl: "https://www.google.com/maps/search/?api=1&query=Grand+Hayat+Sonamarg" }, notes: null },
  // Premium
  { hotelName: "Country Inn & Suites by Radisson Sonamarg", destination: "Sonamarg", category: "PREMIUM", property: { location: "Kargil Road, Sonamarg", contactPerson: null, phone: "+91 60067 50321", email: "reservations.sonamarg@countryinn.com", mapUrl: "https://www.google.com/maps/search/?api=1&query=Country+Inn+%26+Suites+by+Radisson+Sonamarg" }, notes: "4.4★" },
  { hotelName: "Radisson Hotel Sonamarg", destination: "Sonamarg", category: "PREMIUM", property: { location: "Sonamarg, J&K", contactPerson: null, phone: "+91 88990 05266", email: "info.sonamarg@radisson.com", mapUrl: "https://www.google.com/maps/search/?api=1&query=Radisson+Hotel+Sonamarg" }, notes: "4.4★" },
  { hotelName: "Hotel Rosewood Sonamarg", destination: "Sonamarg", category: "PREMIUM", property: { location: "Sonamarg Market", contactPerson: null, phone: "+91 80828 65959 / 01954 254448", email: "reservations@therosewoodsonamarg.com", mapUrl: "https://www.google.com/maps/search/?api=1&query=Hotel+Rosewood+Sonamarg" }, notes: "4.9★" },
  { hotelName: "Four Points by Sheraton Sonmarg Resort", destination: "Sonamarg", category: "PREMIUM", property: { location: "Sonamarg, J&K", contactPerson: null, phone: null, email: null, mapUrl: "https://www.google.com/maps/search/?api=1&query=Four+Points+by+Sheraton+Sonmarg+Resort" }, notes: null },
  { hotelName: "Lemon Tree Hotel, Sonmarg by the Riverside", destination: "Sonamarg", category: "PREMIUM", property: { location: "Sonamarg, J&K", contactPerson: null, phone: null, email: null, mapUrl: "https://www.google.com/maps/search/?api=1&query=Lemon+Tree+Hotel+Sonmarg+by+the+Riverside" }, notes: null },

  // ===== Gurez (docs/gurez-hotels.md) =====
  // Budget
  { hotelName: "The Gurez Perch", destination: "Gurez", category: "BUDGET", property: { location: "Near ITI Wampore, Gurez", contactPerson: null, phone: null, email: null, mapUrl: "https://www.google.com/maps/search/?api=1&query=The+Gurez+Perch" }, notes: "4.5★ / 11 reviews" },
  { hotelName: "GUREZ GUEST HOUSE", destination: "Gurez", category: "BUDGET", property: { location: "Wanpora, Dawar, Gurez", contactPerson: null, phone: null, email: null, mapUrl: "https://www.google.com/maps/search/?api=1&query=Gurez+Guest+House+Dawar" }, notes: "4.5★ / 54 reviews" },
  { hotelName: "Hotel Grand Gurez", destination: "Gurez", category: "BUDGET", property: { location: "Wampora / Khandyal, Gurez", contactPerson: null, phone: "+91 84910 65032", email: null, mapUrl: "https://www.google.com/maps/search/?api=1&query=Hotel+Grand+Gurez" }, notes: "4.0★ / 220 reviews" },
  { hotelName: "GUREZ KNIGHTS Hotel & Restaurant", destination: "Gurez", category: "BUDGET", property: { location: "Mastan Road, Dawar", contactPerson: null, phone: null, email: null, mapUrl: "https://www.google.com/maps/search/?api=1&query=Gurez+Knights+Hotel+Restaurant" }, notes: null },
  { hotelName: "The Gurez Inn Hotel & Restaurant", destination: "Gurez", category: "BUDGET", property: { location: "Near TRC, Dawar", contactPerson: null, phone: "+91 84919 47686", email: null, mapUrl: "https://www.google.com/maps/search/?api=1&query=The+Gurez+Inn+Hotel+Restaurant" }, notes: "4.5★ / 52 reviews" },
  { hotelName: "Hotel Noorani Royale", destination: "Gurez", category: "BUDGET", property: { location: "Dawar, Gurez", contactPerson: null, phone: "+91 70064 86262 / +91 94196 00028", email: "info@nooraniroyale.com / nooraniroyale@gmail.com", mapUrl: "https://www.google.com/maps/search/?api=1&query=Hotel+Noorani+Royale+Gurez" }, notes: null },
  // Deluxe
  { hotelName: "D'SHIEKH'S RESORT GUREZ", destination: "Gurez", category: "DELUXE", property: { location: "Mastan Dawar, Gurez", contactPerson: null, phone: "+91 70068 20480 / +91 77808 01503", email: null, mapUrl: "https://www.google.com/maps/search/?api=1&query=D%27SHIEKH%27S+RESORT+GUREZ" }, notes: "4.7★ / 376 reviews" },
  { hotelName: "PINE TREE RESORT GUREZ", destination: "Gurez", category: "DELUXE", property: { location: "Green Land, Khandyal, Gurez", contactPerson: null, phone: "+91 60057 30427", email: null, mapUrl: "https://www.google.com/maps/search/?api=1&query=Pine+Tree+Resort+Gurez" }, notes: "4.8★ / 267 reviews" },
  { hotelName: "WOOD VIBES", destination: "Gurez", category: "DELUXE", property: { location: "Near TRC, Dawar", contactPerson: null, phone: "+91 91033 65551", email: null, mapUrl: "https://www.google.com/maps/search/?api=1&query=Wood+Vibes+Gurez" }, notes: "4.6★ / 337 reviews" },
  { hotelName: "Calm n Peace SUKOON Resort", destination: "Gurez", category: "DELUXE", property: { location: "Dawar / Gurez Valley", contactPerson: null, phone: "+91 70060 29007", email: null, mapUrl: "https://www.google.com/maps/search/?api=1&query=Calm+n+Peace+Sukoon+Resort+Gurez" }, notes: "4.5★ / 199 reviews" },
  { hotelName: "The Cocoon, Gurez", destination: "Gurez", category: "DELUXE", property: { location: "Dawar, Gurez Valley", contactPerson: null, phone: "+91 98585 85758", email: null, mapUrl: "https://www.google.com/maps/search/?api=1&query=The+Cocoon+Gurez" }, notes: null },
  { hotelName: "ARYAN GRAND PALACE", destination: "Gurez", category: "DELUXE", property: { location: "Wanpora, Gurez", contactPerson: null, phone: null, email: null, mapUrl: "https://www.google.com/maps/search/?api=1&query=Aryan+Grand+Palace+Gurez" }, notes: "4.5★ / 23 reviews" },
  { hotelName: "ZAIM Resort Gurez Valley", destination: "Gurez", category: "DELUXE", property: { location: "Gurez Valley", contactPerson: null, phone: null, email: null, mapUrl: "https://www.google.com/maps/search/?api=1&query=Zaim+Resort+Gurez+Valley" }, notes: "4.9★ / 99 reviews" },
  // Premium (source category label "Premium*" — footnote about conditional classification, mapped to PREMIUM)
  { hotelName: "The Cocoon, Gurez", destination: "Gurez", category: "PREMIUM", property: { location: "Dawar Valley, Gurez", contactPerson: null, phone: "+91 98585 85758", email: null, mapUrl: "https://www.google.com/maps/search/?api=1&query=The+Cocoon+Gurez" }, notes: null },
  { hotelName: "Calm n Peace SUKOON Resort — River View Premium Room", destination: "Gurez", category: "PREMIUM", property: { location: "Kishanganga River, Dawar", contactPerson: null, phone: "+91 70060 29007", email: null, mapUrl: "https://www.google.com/maps/search/?api=1&query=Calm+n+Peace+Sukoon+Resort+Gurez" }, notes: "4.5★ / 199 reviews" },
  { hotelName: "PINE TREE RESORT GUREZ — Deluxe/Valley View", destination: "Gurez", category: "PREMIUM", property: { location: "Khandyal, Gurez", contactPerson: null, phone: "+91 60057 30427", email: null, mapUrl: "https://www.google.com/maps/search/?api=1&query=Pine+Tree+Resort+Gurez" }, notes: "4.8★ / 267 reviews" },

  // ===== Leh / Ladakh & Kargil (docs/leh–ladakh.md) — the doc's Leh section maps
  // to "Leh / Ladakh"; its separate "# Kargil Hotels" section (below) maps to
  // its own "Kargil" destination, not "Leh / Ladakh" =====
  // Budget — Leh
  { hotelName: "The Kart-Sey Ladakh", destination: "Leh / Ladakh", category: "BUDGET", property: { location: "Skara Road, near Zorawar Fort, Leh", contactPerson: null, phone: "+91 95969 24772", email: null, mapUrl: "https://www.google.com/maps/search/?api=1&query=The+Kart-Sey+Ladakh+Leh" }, notes: "4.7★ / 208 reviews" },
  { hotelName: "Ladakh Imperial Leh", destination: "Leh / Ladakh", category: "BUDGET", property: { location: "Skara Road, Leh", contactPerson: null, phone: "+91 99069 99996", email: null, mapUrl: "https://www.google.com/maps/search/?api=1&query=Ladakh+Imperial+Leh" }, notes: "4.7★ / 413 reviews" },
  { hotelName: "Hotel Shambhala", destination: "Leh / Ladakh", category: "BUDGET", property: { location: "Leh", contactPerson: null, phone: null, email: null, mapUrl: "https://www.google.com/maps/search/?api=1&query=Hotel+Shambhala+Leh" }, notes: null },
  { hotelName: "Hotel Lumbini", destination: "Leh / Ladakh", category: "BUDGET", property: { location: "Leh", contactPerson: null, phone: null, email: null, mapUrl: "https://www.google.com/maps/search/?api=1&query=Hotel+Lumbini+Leh" }, notes: null },
  { hotelName: "Hotel Snow View", destination: "Leh / Ladakh", category: "BUDGET", property: { location: "Leh", contactPerson: null, phone: null, email: null, mapUrl: "https://www.google.com/maps/search/?api=1&query=Hotel+Snow+View+Leh" }, notes: null },
  { hotelName: "Hotel Mahay Palace", destination: "Leh / Ladakh", category: "BUDGET", property: { location: "Leh", contactPerson: null, phone: null, email: null, mapUrl: "https://www.google.com/maps/search/?api=1&query=Hotel+Mahay+Palace+Leh" }, notes: null },
  // Deluxe — Leh
  { hotelName: "The Shanti Nest Boutique Hotel", destination: "Leh / Ladakh", category: "DELUXE", property: { location: "Changspa Road, Leh", contactPerson: null, phone: "+91 60055 65188", email: null, mapUrl: "https://www.google.com/maps/search/?api=1&query=The+Shanti+Nest+Boutique+Hotel+Leh" }, notes: "4.7★ / 232 reviews" },
  { hotelName: "Hotel Ladakh Greens", destination: "Leh / Ladakh", category: "DELUXE", property: { location: "Leh", contactPerson: null, phone: null, email: null, mapUrl: "https://www.google.com/maps/search/?api=1&query=Hotel+Ladakh+Greens+Leh" }, notes: null },
  { hotelName: "Ladakh Residency", destination: "Leh / Ladakh", category: "DELUXE", property: { location: "Leh", contactPerson: null, phone: null, email: null, mapUrl: "https://www.google.com/maps/search/?api=1&query=Ladakh+Residency+Leh" }, notes: "4.5★ / 330 reviews" },
  { hotelName: "Hotel Grand Himalaya", destination: "Leh / Ladakh", category: "DELUXE", property: { location: "Leh", contactPerson: null, phone: null, email: null, mapUrl: "https://www.google.com/maps/search/?api=1&query=Hotel+Grand+Himalaya+Leh" }, notes: null },
  { hotelName: "Hotel Naro", destination: "Leh / Ladakh", category: "DELUXE", property: { location: "Leh", contactPerson: null, phone: null, email: null, mapUrl: "https://www.google.com/maps/search/?api=1&query=Hotel+Naro+Leh" }, notes: null },
  { hotelName: "The Bodhi Tree Ladakh", destination: "Leh / Ladakh", category: "DELUXE", property: { location: "Upper Karzoo, Leh", contactPerson: null, phone: null, email: null, mapUrl: "https://www.google.com/maps/search/?api=1&query=The+Bodhi+Tree+Ladakh" }, notes: "4.9★ / 983 reviews" },
  { hotelName: "essence AT LADAKH", destination: "Leh / Ladakh", category: "DELUXE", property: { location: "Near Royal Ladakh, Leh", contactPerson: null, phone: "+91 98102 28660", email: null, mapUrl: "https://www.google.com/maps/search/?api=1&query=Essence+At+Ladakh" }, notes: "4.7★ / 381 reviews" },
  // Premium — Leh
  { hotelName: "The Grand Dragon Ladakh", destination: "Leh / Ladakh", category: "PREMIUM", property: { location: "P. Namgyal Road, Sheynam, Leh", contactPerson: null, phone: "+91 96222 66301", email: null, mapUrl: "https://www.google.com/maps/search/?api=1&query=The+Grand+Dragon+Ladakh" }, notes: "4.5★ / 3,107 reviews" },
  { hotelName: "The Indus River Camp", destination: "Leh / Ladakh", category: "PREMIUM", property: { location: "Leh", contactPerson: null, phone: null, email: null, mapUrl: "https://www.google.com/maps/search/?api=1&query=The+Indus+River+Camp+Leh" }, notes: null },
  { hotelName: "Chospa Hotel Leh", destination: "Leh / Ladakh", category: "PREMIUM", property: { location: "Leh Main Market", contactPerson: null, phone: null, email: null, mapUrl: "https://www.google.com/maps/search/?api=1&query=Chospa+Hotel+Leh" }, notes: null },
  { hotelName: "The Zen Ladakh", destination: "Leh / Ladakh", category: "PREMIUM", property: { location: "Leh", contactPerson: null, phone: null, email: null, mapUrl: "https://www.google.com/maps/search/?api=1&query=The+Zen+Ladakh" }, notes: null },
  { hotelName: "The Apricot Tree Hotel", destination: "Leh / Ladakh", category: "PREMIUM", property: { location: "Leh", contactPerson: null, phone: null, email: null, mapUrl: "https://www.google.com/maps/search/?api=1&query=The+Apricot+Tree+Hotel+Leh" }, notes: null },
  { hotelName: "Hotel Sarai Resort", destination: "Leh / Ladakh", category: "PREMIUM", property: { location: "Leh", contactPerson: null, phone: null, email: null, mapUrl: "https://www.google.com/maps/search/?api=1&query=Hotel+Sarai+Resort+Leh" }, notes: null },
  // Budget — Kargil
  { hotelName: "Hotel Border View", destination: "Kargil", category: "BUDGET", property: { location: "Shelikchay, Kargil", contactPerson: null, phone: "+91 84939 44184", email: null, mapUrl: "https://www.google.com/maps/search/?api=1&query=Hotel+Border+View+Kargil" }, notes: "4.5★ / 410 reviews" },
  { hotelName: "Hotel Larsa", destination: "Kargil", category: "BUDGET", property: { location: "Near New Bus Stand, Kargil", contactPerson: null, phone: "+91 60061 86445", email: null, mapUrl: "https://www.google.com/maps/search/?api=1&query=Hotel+Larsa+Kargil" }, notes: "4.5★ / 36 reviews" },
  { hotelName: "Hotel Rangyul Resort", destination: "Kargil", category: "BUDGET", property: { location: "Khurba Thang, Kargil", contactPerson: null, phone: "+91 88994 52417", email: null, mapUrl: "https://www.google.com/maps/search/?api=1&query=Hotel+Rangyul+Resort+Kargil" }, notes: "4.5★ / 696 reviews" },
  { hotelName: "Hotel Zojila Residency", destination: "Kargil", category: "BUDGET", property: { location: "Bemathang, Baroo, Kargil", contactPerson: null, phone: "+91 94191 76249", email: null, mapUrl: "https://www.google.com/maps/search/?api=1&query=Hotel+Zojila+Residency+Kargil" }, notes: "4.5★ / 298 reviews" },
  { hotelName: "Hotel D'Zojila Kargil", destination: "Kargil", category: "BUDGET", property: { location: "Bemathang, Baroo, Kargil", contactPerson: null, phone: "+91 95968 44033", email: null, mapUrl: "https://www.google.com/maps/search/?api=1&query=Hotel+D%27Zojila+Kargil" }, notes: "4.0★ / 688 reviews" },
  { hotelName: "Hotel Greenland Kargil", destination: "Kargil", category: "BUDGET", property: { location: "Kargil", contactPerson: null, phone: null, email: null, mapUrl: "https://www.google.com/maps/search/?api=1&query=Hotel+Greenland+Kargil" }, notes: null },
  // Deluxe — Kargil (source category labels "Deluxe*" for the last 3 rows — footnote about conditional Budget/Deluxe classification, mapped to DELUXE)
  { hotelName: "The Kargil Hotel", destination: "Kargil", category: "DELUXE", property: { location: "Kargil", contactPerson: null, phone: null, email: null, mapUrl: "https://www.google.com/maps/search/?api=1&query=The+Kargil+Hotel" }, notes: null },
  { hotelName: "Hotel The Kargil", destination: "Kargil", category: "DELUXE", property: { location: "Kargil", contactPerson: null, phone: null, email: null, mapUrl: "https://www.google.com/maps/search/?api=1&query=Hotel+The+Kargil" }, notes: null },
  { hotelName: "Zojila Residency", destination: "Kargil", category: "DELUXE", property: { location: "Bemathang, Kargil", contactPerson: null, phone: "+91 94191 76249", email: null, mapUrl: "https://www.google.com/maps/search/?api=1&query=Hotel+Zojila+Residency+Kargil" }, notes: "4.5★ / 298 reviews" },
  { hotelName: "Hotel D'Zojila Kargil", destination: "Kargil", category: "DELUXE", property: { location: "Bemathang, Kargil", contactPerson: null, phone: "+91 95968 44033", email: null, mapUrl: "https://www.google.com/maps/search/?api=1&query=Hotel+D%27Zojila+Kargil" }, notes: "4.0★ / 688 reviews" },
  { hotelName: "Hotel Rangyul Resort", destination: "Kargil", category: "DELUXE", property: { location: "Khurba Thang, Kargil", contactPerson: null, phone: "+91 88994 52417", email: null, mapUrl: "https://www.google.com/maps/search/?api=1&query=Hotel+Rangyul+Resort+Kargil" }, notes: "4.5★ / 696 reviews" },
  // Premium — Kargil (source category labels "Premium*" for the last 2 rows, mapped to PREMIUM)
  { hotelName: "The Kargil Sarai Resort", destination: "Kargil", category: "PREMIUM", property: { location: "Kargil", contactPerson: null, phone: null, email: null, mapUrl: "https://www.google.com/maps/search/?api=1&query=The+Kargil+Sarai+Resort" }, notes: null },
  { hotelName: "The Highland Mountain Resort", destination: "Kargil", category: "PREMIUM", property: { location: "Kargil", contactPerson: null, phone: null, email: null, mapUrl: "https://www.google.com/maps/search/?api=1&query=The+Highland+Mountain+Resort+Kargil" }, notes: null },
  { hotelName: "Hotel Zojila Residency — Premium Room", destination: "Kargil", category: "PREMIUM", property: { location: "Bemathang, Kargil", contactPerson: null, phone: "+91 94191 76249", email: null, mapUrl: "https://www.google.com/maps/search/?api=1&query=Hotel+Zojila+Residency+Kargil" }, notes: "4.5★ / 298 reviews" },
  { hotelName: "Hotel Rangyul Resort — Premium Room", destination: "Kargil", category: "PREMIUM", property: { location: "Khurba Thang, Kargil", contactPerson: null, phone: "+91 88994 52417", email: null, mapUrl: "https://www.google.com/maps/search/?api=1&query=Hotel+Rangyul+Resort+Kargil" }, notes: "4.5★ / 696 reviews" },

  // ===== Katra / Vaishno Devi (docs/Vaishno-Devi-Katra-hotels.md) =====
  // Budget
  { hotelName: "The Vaishno Devi Hills Katra", destination: "Katra / Vaishno Devi", category: "BUDGET", property: { location: "Jammu Road, near Guru Nanak Parking", contactPerson: null, phone: "+91 95964 54369", email: null, mapUrl: "https://www.google.com/maps/search/?api=1&query=The+Vaishno+Devi+Hills+Katra" }, notes: "4.4★ / 725 reviews" },
  { hotelName: "Hotel Katra Hills", destination: "Katra / Vaishno Devi", category: "BUDGET", property: { location: "Railway Road, opposite J&K Bank", contactPerson: null, phone: "+91 80825 40637", email: null, mapUrl: "https://www.google.com/maps/search/?api=1&query=Hotel+Katra+Hills" }, notes: "4.5★ / 181 reviews" },
  { hotelName: "Ganpati Hotel Katra", destination: "Katra / Vaishno Devi", category: "BUDGET", property: { location: "Katra", contactPerson: null, phone: null, email: null, mapUrl: "https://www.google.com/maps/search/?api=1&query=Ganpati+Hotel+Katra" }, notes: "4.3★ / 221 reviews" },
  { hotelName: "Hotel The Vaishvik", destination: "Katra / Vaishno Devi", category: "BUDGET", property: { location: "Katra", contactPerson: null, phone: null, email: null, mapUrl: "https://www.google.com/maps/search/?api=1&query=Hotel+The+Vaishvik+Katra" }, notes: "4.4★ / 313 reviews" },
  { hotelName: "Hotel Ambica Katra", destination: "Katra / Vaishno Devi", category: "BUDGET", property: { location: "Main Market, Katra", contactPerson: null, phone: null, email: null, mapUrl: "https://www.google.com/maps/search/?api=1&query=Hotel+Ambica+Katra" }, notes: "4.4★ / ~1,500 reviews" },
  { hotelName: "Hotel Asia Vaishno Devi", destination: "Katra / Vaishno Devi", category: "BUDGET", property: { location: "Katra", contactPerson: null, phone: null, email: null, mapUrl: "https://www.google.com/maps/search/?api=1&query=Hotel+Asia+Vaishno+Devi+Katra" }, notes: null },
  // Deluxe
  { hotelName: "Hotel The Royal Krishna", destination: "Katra / Vaishno Devi", category: "DELUXE", property: { location: "Katra", contactPerson: null, phone: null, email: null, mapUrl: "https://www.google.com/maps/search/?api=1&query=Hotel+The+Royal+Krishna+Katra" }, notes: "4.3★ / ~1,300 reviews" },
  { hotelName: "The Fern Residency, Katra", destination: "Katra / Vaishno Devi", category: "DELUXE", property: { location: "Near Katra Railway Station", contactPerson: null, phone: null, email: null, mapUrl: "https://www.google.com/maps/search/?api=1&query=The+Fern+Residency+Katra" }, notes: "4.5★ / 1,737 reviews" },
  { hotelName: "Hotel Rama Trident", destination: "Katra / Vaishno Devi", category: "DELUXE", property: { location: "Katra", contactPerson: null, phone: null, email: null, mapUrl: "https://www.google.com/maps/search/?api=1&query=Hotel+Rama+Trident+Katra" }, notes: null },
  { hotelName: "Fortune Park, Katra", destination: "Katra / Vaishno Devi", category: "DELUXE", property: { location: "Station Road, Katra", contactPerson: null, phone: "+91 199 1350000 / +91 9055115115", email: "katra@fortunehotels.in", mapUrl: "https://www.google.com/maps/search/?api=1&query=Fortune+Park+Katra" }, notes: null },
  { hotelName: "Hotel Katra Residency", destination: "Katra / Vaishno Devi", category: "DELUXE", property: { location: "Katra", contactPerson: null, phone: null, email: null, mapUrl: "https://www.google.com/maps/search/?api=1&query=Hotel+Katra+Residency" }, notes: null },
  { hotelName: "Hotel Devi Grand", destination: "Katra / Vaishno Devi", category: "DELUXE", property: { location: "Katra", contactPerson: null, phone: null, email: null, mapUrl: "https://www.google.com/maps/search/?api=1&query=Hotel+Devi+Grand+Katra" }, notes: "3.8★ / ~1,000 reviews" },
  // Premium
  { hotelName: "Vivanta Katra, Vaishno Devi", destination: "Katra / Vaishno Devi", category: "PREMIUM", property: { location: "Jammu–Katra Highway, Manun", contactPerson: null, phone: "+91 1991 350200", email: "bookvivanta.katra@tajhotels.com", mapUrl: "https://www.google.com/maps/search/?api=1&query=Vivanta+Katra+Vaishno+Devi" }, notes: "4.5★ / 1,824 reviews" },
  { hotelName: "Welcomhotel by ITC Hotels, Katra", destination: "Katra / Vaishno Devi", category: "PREMIUM", property: { location: "Jammu–Katra Highway", contactPerson: null, phone: null, email: null, mapUrl: "https://www.google.com/maps/search/?api=1&query=Welcomhotel+by+ITC+Hotels+Katra" }, notes: "4.6★ / 1,505 reviews" },
  { hotelName: "Holiday Inn Katra Vaishno Devi", destination: "Katra / Vaishno Devi", category: "PREMIUM", property: { location: "Katra Railway Station Road", contactPerson: null, phone: "+91 1991 350350", email: "info@holidayinnkatra.com", mapUrl: "https://www.google.com/maps/search/?api=1&query=Holiday+Inn+Katra+Vaishno+Devi" }, notes: "4.8★ / ~3,700 reviews" },
  { hotelName: "The Vaishnodevi Sarovar Portico", destination: "Katra / Vaishno Devi", category: "PREMIUM", property: { location: "Jammu–Katra Highway, Vaishnodevi", contactPerson: null, phone: null, email: null, mapUrl: "https://www.google.com/maps/search/?api=1&query=The+Vaishnodevi+Sarovar+Portico" }, notes: "4.5★ / ~1,600 reviews" },
  { hotelName: "Country Inn & Suites by Radisson Katra", destination: "Katra / Vaishno Devi", category: "PREMIUM", property: { location: "Katra", contactPerson: null, phone: null, email: null, mapUrl: "https://www.google.com/maps/search/?api=1&query=Country+Inn+%26+Suites+by+Radisson+Katra" }, notes: null },
  { hotelName: "AMR Hotel & Resorts", destination: "Katra / Vaishno Devi", category: "PREMIUM", property: { location: "Katra", contactPerson: null, phone: null, email: null, mapUrl: "https://www.google.com/maps/search/?api=1&query=AMR+Hotel+%26+Resorts+Katra" }, notes: null },

  // ===== Uri / Kaman Setu (docs/ Kaman-Setu-Uri-Hotels.md) =====
  // Budget — Uri
  { hotelName: "Hotel Green Park Uri", destination: "Uri / Kaman Setu", category: "BUDGET", property: { location: "Uri", contactPerson: null, phone: null, email: null, mapUrl: "https://www.google.com/maps/search/?api=1&query=Hotel+Green+Park+Uri+Jammu+Kashmir" }, notes: null },
  { hotelName: "Hotel Royal Plaza Uri", destination: "Uri / Kaman Setu", category: "BUDGET", property: { location: "Uri", contactPerson: null, phone: null, email: null, mapUrl: "https://www.google.com/maps/search/?api=1&query=Hotel+Royal+Plaza+Uri+Jammu+Kashmir" }, notes: null },
  { hotelName: "Hotel New Tourist Lodge Uri", destination: "Uri / Kaman Setu", category: "BUDGET", property: { location: "Uri", contactPerson: null, phone: null, email: null, mapUrl: "https://www.google.com/maps/search/?api=1&query=Hotel+New+Tourist+Lodge+Uri+Jammu+Kashmir" }, notes: null },
  { hotelName: "Hotel Grand Uri", destination: "Uri / Kaman Setu", category: "BUDGET", property: { location: "Uri", contactPerson: null, phone: null, email: null, mapUrl: "https://www.google.com/maps/search/?api=1&query=Hotel+Grand+Uri+Jammu+Kashmir" }, notes: null },
  { hotelName: "Uri Guest House", destination: "Uri / Kaman Setu", category: "BUDGET", property: { location: "Uri", contactPerson: null, phone: null, email: null, mapUrl: "https://www.google.com/maps/search/?api=1&query=Uri+Guest+House+Jammu+Kashmir" }, notes: null },
  // Deluxe — Uri / Baramulla
  { hotelName: "Hotel Pine View Uri", destination: "Uri / Kaman Setu", category: "DELUXE", property: { location: "Uri", contactPerson: null, phone: null, email: null, mapUrl: "https://www.google.com/maps/search/?api=1&query=Hotel+Pine+View+Uri+Jammu+Kashmir" }, notes: null },
  { hotelName: "Hotel New Park Uri", destination: "Uri / Kaman Setu", category: "DELUXE", property: { location: "Uri", contactPerson: null, phone: null, email: null, mapUrl: "https://www.google.com/maps/search/?api=1&query=Hotel+New+Park+Uri+Jammu+Kashmir" }, notes: null },
  { hotelName: "Hotel Apple Tree Uri", destination: "Uri / Kaman Setu", category: "DELUXE", property: { location: "Uri", contactPerson: null, phone: null, email: null, mapUrl: "https://www.google.com/maps/search/?api=1&query=Hotel+Apple+Tree+Uri+Jammu+Kashmir" }, notes: null },
  { hotelName: "Hotel Royal Park Uri", destination: "Uri / Kaman Setu", category: "DELUXE", property: { location: "Uri", contactPerson: null, phone: null, email: null, mapUrl: "https://www.google.com/maps/search/?api=1&query=Hotel+Royal+Park+Uri+Jammu+Kashmir" }, notes: null },
  { hotelName: "Hotel Highway Inn Baramulla", destination: "Uri / Kaman Setu", category: "DELUXE", property: { location: "Baramulla", contactPerson: null, phone: null, email: null, mapUrl: "https://www.google.com/maps/search/?api=1&query=Hotel+Highway+Inn+Baramulla" }, notes: null },
  // Premium — Srinagar / Baramulla Base
  { hotelName: "The Lalit Grand Palace Srinagar", destination: "Uri / Kaman Setu", category: "PREMIUM", property: { location: "Gupkar Road, Srinagar", contactPerson: null, phone: "+91 194 2501001", email: "srinagar@thelalit.com", mapUrl: "https://www.google.com/maps/search/?api=1&query=The+Lalit+Grand+Palace+Srinagar" }, notes: "4.3★" },
  { hotelName: "Taj Dal View Srinagar", destination: "Uri / Kaman Setu", category: "PREMIUM", property: { location: "Kralsangri, Brein, Srinagar", contactPerson: null, phone: "+91 194 2461111", email: "tajdalview.srinagar@tajhotels.com", mapUrl: "https://www.google.com/maps/search/?api=1&query=Taj+Dal+View+Srinagar" }, notes: "4.5★" },
  { hotelName: "Radisson Collection Hotel & Spa Riverfront Srinagar", destination: "Uri / Kaman Setu", category: "PREMIUM", property: { location: "Rajbagh, Srinagar", contactPerson: null, phone: "+91 194 2310111", email: null, mapUrl: "https://www.google.com/maps/search/?api=1&query=Radisson+Collection+Hotel+Spa+Riverfront+Srinagar" }, notes: "4.8★" },
];
