ALTER TABLE "Lead" ADD COLUMN IF NOT EXISTS "negotiatedAmount" DOUBLE PRECISION;
ALTER TABLE "Lead" ADD COLUMN IF NOT EXISTS "tokenAmount" DOUBLE PRECISION;
ALTER TABLE "Lead" ADD COLUMN IF NOT EXISTS "followUpAt" TIMESTAMP(3);
CREATE INDEX IF NOT EXISTS "Lead_followUpAt_idx" ON "Lead"("followUpAt");
